language: php

matrix:
  include:
    - php: 8.1
      dist: bionic
    - php: nightly
      dist: bionic
  fast_finish: true
  allow_failures:
    - php: nightly

install:
  - composer install --prefer-dist

script:
  - travis/run-phpunit.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)
