language: php

matrix:
  include:
    - php: 5.6
      dist: xenial
    - php: 7.0
      dist: xenial
    - php: 7.1
      dist: xenial
    - php: 7.2
      dist: xenial
    - php: 7.3
      dist: xenial
    - php: 7.4
      dist: xenial
    - php: 8.0
      dist: bionic
    - php: 8.1.0
      dist: bionic
    - php: nightly
      dist: bionic
  fast_finish: true
  allow_failures:
    - php: nightly

install:
  - composer install --prefer-dist

script:
  - travis/run-phpunit.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)
